repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v3.6.0"
    hooks:
      - id: prettier
        args: [--single-quote] #list of args like '--single-quote', '--jsx-bracket-same-line', '--print-width 120', '--no-bracket-spacing'
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0 # Use the ref you want to point at
    hooks:
      - id: trailing-whitespace
      - id: check-added-large-files
        args: [--maxkb=3000]
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-vcs-permalinks
      - id: check-yaml
      - id: detect-private-key
      - id: end-of-file-fixer
      - id: mixed-line-ending
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.18.0 # Use the sha / tag you want to point at
    hooks:
      - id: eslint
        files: \.[jt]sx?$  # *.js, *.jsx, *.ts and *.tsx
        types: [ file ]
        args: ['--fix']
        additional_dependencies:
          - eslint@7.22.0
          - eslint-config-airbnb@18.2.1
          - eslint-config-prettier@6.15.0
          - eslint-plugin-eslint-plugin@2.3.0
          - eslint-plugin-import@2.22.1
          - eslint-plugin-jest@24.3.1
          - eslint-plugin-json@2.1.2
files: 'packages/'
